####################################
# Automatically generated by SMake #
# https://github.com/kala13x/smake #
####################################

CFLAGS =  -I.
LIBS = 
NAME = main
ODIR = .
OBJ = o

OBJS = main.$(OBJ) \
	task.$(OBJgithub theme) \
	taskList.$(OBJ)

OBJECTS = $(patsubst %,$(ODIR)/%,$(OBJS))

.c.$(OBJ):
	@test -d $(ODIR) || mkdir -p $(ODIR)
	$(CC) $(CFLAGS) -c -o $(ODIR)/$@ $< $(LIBS)

$(NAME):$(OBJS)
	$(CC) $(CFLAGS) -o $(ODIR)/$(NAME) $(OBJECTS) $(LIBS)

.PHONY: clean
clean:
	$(RM) $(ODIR)/$(NAME) $(OBJECTS)
